### ISSUE TITLE
Nuget package Dotspatial.Plugins.Menubar "cannot be restored"

### ISSUE THREAD

**Issue by pedwik** [FObermaier/DotSpatial.Plugins#10]
Opened the solution it in Visual Studio 2015 and tried to build. Problem with Nuget packages, but when trying to restore them there is an error message saying "Unable to find version '1.0.1195' of package 'Dotspatial.Plugins.Menubar' ". Similar message in VS 2013.

**Comment by FObermaier** [comment]
Fixed with 0cccedc275b5b6f495f639939ba0c478caa8426e
