### ISSUE TITLE
NetTopologySuite.NtsGeometryServices.Instance code typo?

### ISSUE THREAD

**Issue by pedwik** [FObermaier/DotSpatial.Plugins#11]
When trying to build the latest version there is an error in FeatureSetFromSqlServer.cs, "saying Cannot resolve NetTopologySuite", line 17: 

`GeoAPI.GeometryServiceProvider.Instance = new NetTopologySuite. NetTopologySuite.NtsGeometryServices.Instance;`

Obviously there is a typo, changing it to 
`GeoAPI.GeometryServiceProvider.Instance = NetTopologySuite.NtsGeometryServices.Instance`

solves it.

**Comment by FObermaier** [comment]
Fixed with 0cccedc275b5b6f495f639939ba0c478caa8426e
