### ISSUE TITLE
How to use  DotSpatial.Plugins.Database with PostgreSQL

### ISSUE THREAD

**Issue by rupakraj** [FObermaier/DotSpatial.Plugins#13]
Hello 
I was trying to load map from **PostgreSQL**/**PostGIS** database. My table is as below 

`CREATE TABLE public.parcel
(
  gid integer NOT NULL DEFAULT nextval('parcel_gid_seq'::regclass),
  objectid integer,
  objectno integer,
  shape_length numeric,
  shape_area numeric,
  note character varying(200),
  geom geometry(Polygon)
)`

How can I load the table's geom field into the map? 
Where can I get the sample implementation?

**Comment by FObermaier** [comment]
``` C#
var pg = new DotSpatial.Plugins.Database.PostGisVectorProvider();
var ds = pg.Open(connectionString, "public", "parcel", "gid", "geom");
map.Layers.Add(ds);
```

You might run into trouble because you have not set a spatial reference system for your postgis table.
