### ISSUE TITLE
Exception when adding WMTS-connection

### ISSUE THREAD

**Issue by pedwik** [FObermaier/DotSpatial.Plugins#6]
A null-reference exception occurs on line 129 in ucWmtsLayerConfiguration.cs when connectiong to this url: 

http://maps-open.lantmateriet.se/open/topowebb-ccby/v1/wmts?request=GetCapabilities&version=1.0.0&service=wmts

**Comment by FObermaier** [comment]
This is an exception thrown within the [BruTile](https://github.com/BruTile/BruTile) library's `WmtsParser.Parse` function.

**Comment by pauldendulk** [comment]
@pedwik Do you know how this capabilities is created? What kind of technology is underneath this service? Basically the xml is incorrect because some element are missing the 'ows' namespace. Preferably BruTile should work correctly despite this but it would be nice if the service could be fixed too.

**Comment by pedwik** [comment]
Hi!
I do not know the details, it is a service provided by the Swedish state
agency Lantmäteriet (!). http://www.lantmateriet.se/en/

Here are the specs I have found:
http://www.lantmateriet.se/globalassets/kartor-och-geografisk-information/geodatatjanster/tekn_beskrivningar/tb_twkvisningvccby_v1.0.pdf

It is mainly in Swedish but most of the (short) text seems "universal".

If you like, I can submit your question as a support ticket to them.

Best regards,
Peder

2015-08-05 10:16 GMT+02:00 Paul den Dulk <notifications@github.com>:

**Comment by FObermaier** [comment]
@pedwik,  @pauldendulk,
since this is a BruTile issue, I'd prefer to further persue [this issue](https://github.com/BruTile/BruTile/issues/25) 
Thanks

**Comment by pauldendulk** [comment]
I'm sorry. I posted here to reach the orginal poster but I see I can also @ him on the BruTile issue.
