### ISSUE TITLE
ProjectionInfo is null

### ISSUE THREAD

**Issue by pedwik** [FObermaier/DotSpatial.Plugins#9]
In BruTileLayer.cs line 224, the projection info is retrieved usng the srs code from the tileSource.Schema.Srs string. This code for example has value urn:ogc:def:crs:EPSG:6.18.3:3857. The code is passed to DotSpatial.Projections.AuthorityCodeHandler.Instance[src]. It appears to me that AuthorityCodeHandler does not handle this kind of format but expects a string such as "EPSG:3857", so the returned projectionInfo is always null, at least in the cases I have tried. In BrutileLayer the projection EPSG:3857 is set be default if the projectionInfo is null.

**Comment by FObermaier** [comment]
@pedwik: Could you please verify

**Comment by pedwik** [comment]
I do not know how to verify but AuthorityCodeToProj4.txt in DotSpatial.Projections\AuthorityCodes\AuthorityCodeToProj4.txt only contains codes of the form EPSG:number. Using this works for me but I do not know if it covers all cases:
if (tileSource.Schema.Srs.Contains("EPSG"))
                {
                    string[] s = tileSource.Schema.Srs.Split(':');
                    // The code is always (?) the last element of the split string
                    string tmpEpsg = s.GetValue(s.Length - 1).ToString();
                    int tryEspg;
                    if (int.TryParse(tmpEpsg, out tryEspg))
                    {
                        _projectionInfo = AuthorityCodeHandler.Instance["EPSG:" + tryEspg];
                    }
                }
